[meta]
problem_size_names = ['in_channels', 'out_channels']

["NVIDIA GeForce RTX 5070"]
  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [16, 16]
  IMPL_ID = 0
  SWAP_GRAD_X = false

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [16, 32]
  IMPL_ID = 0
  SWAP_GRAD_X = false

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [32, 16]
  IMPL_ID = 0
  SWAP_GRAD_X = true

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [32, 32]
  IMPL_ID = 0
  SWAP_GRAD_X = false

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [32, 64]
  IMPL_ID = 0
  SWAP_GRAD_X = false

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [64, 32]
  IMPL_ID = 0
  SWAP_GRAD_X = true

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [64, 64]
  IMPL_ID = 1
  SWAP_GRAD_X = false

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [64, 128]
  IMPL_ID = 1
  SWAP_GRAD_X = false

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [128, 64]
  IMPL_ID = 1
  SWAP_GRAD_X = false

  [["NVIDIA GeForce RTX 5070".configs]]
  problem_sizes = [128, 128]
  IMPL_ID = 1
  SWAP_GRAD_X = false
